# Generated by Django 5.0.2 on 2024-02-08 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instructor_evaluation_grade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="عنوان")),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="کد"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="عنوان")),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=20, verbose_name="کد")),
                (
                    "month_start",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        verbose_name="ماه شروع",
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1390),
                            django.core.validators.MaxValueValidator(1450),
                        ],
                        verbose_name="سال شروع",
                    ),
                ),
                (
                    "month_end",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        verbose_name="ماه پایان",
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1390),
                            django.core.validators.MaxValueValidator(1450),
                        ],
                        verbose_name="سال پایان",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="محل برگزاری"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("ش", "شنبه"),
                            ("ی", "یک\u200cشنبه"),
                            ("د", "دوشنبه"),
                            ("س", "سه\u200cشنبه"),
                            ("چ", "چهارشنبه"),
                            ("پ", "پنج\u200cشنبه"),
                            ("ج", "جمعه"),
                        ],
                        max_length=1,
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.coursetitle",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.instructor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.program",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.programtitle",
                verbose_name="عنوان",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.semester",
                verbose_name="ترم",
            ),
        ),
    ]
