# Generated by Django 5.0.1 on 2024-02-16 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_course_instructor_evaluation_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="group",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="گروه",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.instructor",
                verbose_name="مدرس",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor_evaluation_grade",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="نمره ارزیابی مدرس",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.program",
                verbose_name="دوره",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.coursetitle",
                verbose_name="عنوان",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coursesession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.course",
                verbose_name="درس",
            ),
        ),
    ]
