# Generated by Django 5.0.2 on 2024-02-18 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_coursesession_group_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year_start', 'month_start']},
        ),
        migrations.AddField(
            model_name='semester',
            name='day_end',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز پایان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='day_start',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز شروع'),
            preserve_default=False,
        ),
    ]
