# Generated by Django 5.0.2 on 2024-02-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_semester_options_semester_day_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.program', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='program',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.semester', verbose_name='ترم'),
        ),
    ]
