# Generated by Django 5.0.2 on 2024-02-20 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_course_program_alter_program_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='group',
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='گروه'),
        ),
    ]
