# Generated by Django 5.0.1 on 2024-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_remove_coursesession_group_course_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetitle",
            name="title",
            field=models.CharField(max_length=80, unique=True, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="programtitle",
            name="title",
            field=models.CharField(max_length=80, unique=True, verbose_name="عنوان"),
        ),
    ]
